# Generated by Django 4.2 on 2023-04-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('born_date', models.DateTimeField(verbose_name='born_date')),
                ('born_location', models.CharField()),
                ('description', models.CharField()),
            ],
        ),
    ]
