# Generated by Django 4.2 on 2023-04-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_tag_alter_author_description_remove_quote_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='fullname',
            field=models.TextField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
